In [39]:
import numpy as np

array = (np.full((1,6),2) ** np.arange(0,6)).reshape(2,3)
flattened = array.flatten()
print(flattened)
print(array)

raveled = array.ravel()
print(raveled)
print(array)

raveled[0]=0

print(raveled)
print(array)

[ 1  2  4  8 16 32]
[[ 1  2  4]
 [ 8 16 32]]
[ 1  2  4  8 16 32]
[[ 1  2  4]
 [ 8 16 32]]
[ 0  2  4  8 16 32]
[[ 0  2  4]
 [ 8 16 32]]
