In [7]:
import numpy as np
import random as rd

def mode_array(array):
    
    array_test = np.bincount(array.flatten())
    return np.where(array_test==max(array_test))[0]
    
def median_array(array):
    array_test = np.sort(array.flatten())
    if len(array_test)%2==0:
        x = int(len(array_test)/2)
        y = int((len(array_test)/2)+1)
        value = array_test[x] + array_test[y]
     
        return value/2
    else:
        x = (int(len(array_test)/2)+1)-1
        return array_test[x]
        
array = np.array([rd.randrange(0,100) for i in range(36)]).reshape(6,6)
print(array)

print(f'Median {median_array(array)}')

[[37 80 80 31 53 26]
 [23 87 87 24 28 54]
 [68 23 77 53 55 49]
 [90 72 18 72 45 15]
 [86 12 98 79 17 93]
 [22 90 18 21  9 85]]
Median 53.5
