In [22]:
import numpy as np
import random as rd

array = np.array([rd.randrange(0,100) for i in range(25)]).reshape(5,5)
print(array)

print(np.bincount(array.flatten()))


[[28 69 14 34 25]
 [25  0 37 26 61]
 [69 16 10 19 49]
 [41 16 37 40 57]
 [41 21  2 31 82]]
[1 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 2 0 0 1 0 1 0 0 0 2 1 0 1 0 0 1 0 0 1 0 0
 2 0 0 1 2 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 2 0 0 0 0
 0 0 0 0 0 0 0 0 1]
