In [35]:
import numpy as np
import random as rd

def mode_array_2d(array, axis):

    text = ''
    
    if axis==0:
        for i in array:
            array_test = np.bincount(i)
            text += f'{i} : {np.where(array_test==max(array_test))[0]}\n'
        return text
    elif axis==1:
        for i in array.T:
            array_test = np.bincount(i)
            text += f'{i} : {np.where(array_test==max(array_test))[0]}\n'
        return text
    else:
        return f'Error: Axis must be 1 or 0'

    
def median_array_2d(array, axis):
    
    text = ''
    
    if axis==0:
        for i in array:
            array_test = np.sort(i)
            if len(array_test)%2==0:
                x = int(len(array_test)/2)
                y = int((len(array_test)/2)+1)
                value = array_test[x] + array_test[y]
                text += f'{array_test} : {value/2}\n'
            else:
                x = (int(len(array_test)/2)+1)-1
                text += f'{array_test} : {array_test[x]}\n'
        return text
        
    elif axis==1:
        for i in array.T:
            array_test = np.sort(i)
            if len(array_test)%2==0:
                x = int(len(array_test)/2)
                y = int((len(array_test)/2)+1)
                value = array_test[x] + array_test[y]           
                text += f'{array_test} : {value/2}\n'
            else:
                x = (int(len(array_test)/2)+1)-1
                text += f'{array_test} : {array_test[x]}\n'
        return text
    else:
        return f'Error: Axis must be 1 or 0'
    

array = np.array([rd.randrange(0,100) for i in range(36)]).reshape(6,6)

print(mode_array_2d(array,0))
print(median_array_2d(array,1))

[23 93 90 71 46  7] : [ 7 23 46 71 90 93]
[28 22 43 27 40 20] : [20 22 27 28 40 43]
[74 93 77 54 73 63] : [54 63 73 74 77 93]
[53 65 75 10  3 93] : [ 3 10 53 65 75 93]
[ 1 32  7 87 85 95] : [ 1  7 32 85 87 95]
[ 4  1  1 52 81 44] : [1]

[ 1  4 23 28 53 74] : 40.5
[ 1 22 32 65 93 93] : 79.0
[ 1  7 43 75 77 90] : 76.0
[10 27 52 54 71 87] : 62.5
[ 3 40 46 73 81 85] : 77.0
[ 7 20 44 63 93 95] : 78.0

