In [19]:
import numpy as np

array = np.arange(1,16).reshape(3,5)
print(array)
print()
print(array[2])#a
print(array[:,4:5])#b
print(array[0:2])#c
print(array[:,2:5])#d
print(array[1][4])#e
print(array[1:3,[0,2,4]])#f

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

[11 12 13 14 15]
[[ 5]
 [10]
 [15]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]
10
[[ 6  8 10]
 [11 13 15]]
