In [122]:
import numpy as np

def print_array(x,y,array):
    conty = 0
    contx = 1

    if len(array)!=(x*y):
        raise ValueError(f'cannot make array of size {len(array)} into shape ({x},{y})')
    
    length=len(str(array.max()))
  
    print('[',end='')
    for i in range(len(array)):
        if i==0:
            print('[',end='')
        print(f'{array[i]:>{length}}',end='')
        conty+=1
        if conty==y and contx<x:
            print(']',end='')
            conty=0
            contx+=1    
            print()
            print(' [',end='')
        else:
            if i==len(array)-1:
                print(']]')
            else:
                print(end=' ')
    print()
    
array = np.arange(0,25)


print_array(5,5,array)

#comparation with numpy
array2 = np.arange(0,25).reshape(5,5)
       
print(array2)
   
       

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
