In [16]:
import numpy as np

array = np.array([x for x in range(2,19) if x%2==0]).reshape(3,3)

array2 = np.array([x for x in range(9,0,-1)]).reshape(3,3)

print(array*array2)

[[18 32 42]
 [48 50 48]
 [42 32 18]]
