In [6]:
import numpy as np

array1 = np.array([[0,1],[2,3]])
array2 = np.array([[4,5],[6,7]])

array3 = np.vstack((array1,array2))

array4 = np.hstack((array1,array2))

array5 = np.vstack((array4,array4))

array6 = np.hstack((array3,array3))

print(array3)

print(array4)

print(array5)

print(array6)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0 1 4 5]
 [2 3 6 7]]
[[0 1 4 5]
 [2 3 6 7]
 [0 1 4 5]
 [2 3 6 7]]
[[0 1 0 1]
 [2 3 2 3]
 [4 5 4 5]
 [6 7 6 7]]
